version: '3'
services:
  cassandra:
    build: ./cassandra/
    volumes:
      - ./cassandra/db/var:/var/lib/cassandra
    container_name: cassandra-test
  cassandra-test-load-data:
    build: ./cassandra/
    volumes:
      - ./cassandra/db/simple.cql:/simple.cql
    container_name: cassandra-test-load-data
    entrypoint: ["dockerize", "-timeout", "60s", "-wait", "tcp://cassandra-test:9042"]
    command: ["cqlsh", "cassandra", "-f", "/simple.cql"]
    depends_on:
      - cassandra
