version: '3'
services:
  cassandra:
    image: cassandra:latest
    volumes:
      - ./cassandra/db/var:/var/lib/cassandra
    container_name: cassandra-test
  cassandra-test-dockerize:
    # To wait for cassandra startup
    image: jwilder/dockerize
    container_name: cassandra-test-dockerize
    entrypoint: dockerize -wait tcp://cassandra-test:9042 -timeout 30s
    depends_on:
      - cassandra
  cassandra-test-load-data:
    container_name: cassandra-test-load-data
    image: cassandra:latest
    depends_on:
      - cassandra-test-dockerize
    volumes:
      - ./cassandra/db/simple.cql:/tmp/simple.cql
    entrypoint: cqlsh cassandra -f /tmp/simple.cql"
