version: '3'
services:
  cassandra1:
    build: ./cassandra/
    volumes:
      - ./cassandra/db/var/cassandra1:/var/lib/cassandra
    container_name: cassandra-test1
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
  cassandra2:
    build: ./cassandra/
    volumes:
      - ./cassandra/db/var/cassandra2:/var/lib/cassandra
    container_name: cassandra-test2
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    depends_on:
      - cassandra1
  cassandra3:
    build: ./cassandra/
    volumes:
      - ./cassandra/db/var/cassandra3:/var/lib/cassandra
    container_name: cassandra-test3
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    depends_on:
      - cassandra2
  load-data:
    build: ./cassandra/
    volumes:
      - ./cassandra/db/simple.cql:/simple.cql
    container_name: cassandra-test-load-data
    environment:
      - CASSANDRA_SEEDS=cassandra1
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    entrypoint:
      - dockerize
      - -timeout
      - 3m
      - -wait
      - tcp://cassandra-test1:9042
      - -wait
      - tcp://cassandra-test2:9042
      - -wait
      - tcp://cassandra-test3:9042
    command: ["cqlsh", "cassandra-test1", "-f", "/simple.cql"]
    depends_on:
      - cassandra1
      - cassandra2
      - cassandra3
